import type { JsonValue } from "./json";

/** Roles understood by the provider-neutral conversation model. */
export type MessageRole = "system" | "user" | "assistant" | "tool";

/** A text segment in multipart message content. */
export interface TextContentPart {
  readonly type: "text";
  readonly text: string;
}

/** A remotely hosted image segment. Provider support is capability-dependent. */
export interface ImageUrlContentPart {
  readonly type: "image_url";
  readonly imageUrl: string;
  readonly mediaType?: string;
}

/** Content that can appear in a chat message. */
export type ContentPart = TextContentPart | ImageUrlContentPart;

/** A message body, either plain text or a sequence of typed content segments. */
export type MessageContent = string | readonly ContentPart[];

/**
 * A model-requested function invocation.
 *
 * Arguments intentionally remain a string. Validation belongs to the tool
 * runtime, which can report malformed model output without losing the raw value.
 */
export interface ToolCall {
  readonly id: string;
  readonly name: string;
  readonly arguments: string;
}

interface BaseMessage {
  readonly content: MessageContent;
  readonly metadata?: Readonly<Record<string, JsonValue>>;
  readonly name?: string;
}

/** A system-level instruction. */
export interface SystemMessage extends BaseMessage {
  readonly role: "system";
}

/** A message supplied by the end user. */
export interface UserMessage extends BaseMessage {
  readonly role: "user";
}

/** A message generated by an assistant. */
export interface AssistantMessage extends BaseMessage {
  readonly role: "assistant";
  readonly toolCalls?: readonly ToolCall[];
}

/** The result returned by a previously requested tool call. */
export interface ToolMessage extends BaseMessage {
  /** Name of the function that produced this result. */
  readonly name: string;
  readonly role: "tool";
  readonly toolCallId: string;
}

/** A provider-neutral conversation message. */
export type ChatMessage = SystemMessage | UserMessage | AssistantMessage | ToolMessage;
